# Generated by Django 3.2 on 2023-09-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('made', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.category')),
            ],
        ),
    ]
